"""Initial schema

Revision ID: 998ad443b9f7
Revises: 
Create Date: 2026-04-22 17:22:44.985763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998ad443b9f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_institution_id'), ['institution_id'], unique=False)
        batch_op.create_foreign_key(None, 'institutions', ['institution_id'], ['id'])

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_subjects_code'))
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_institution_id'), ['institution_id'], unique=False)
        batch_op.create_unique_constraint('uq_subject_institution_code', ['institution_id', 'code'])
        batch_op.create_foreign_key(None, 'institutions', ['institution_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_institution_id'), ['institution_id'], unique=False)
        batch_op.create_foreign_key(None, 'institutions', ['institution_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_institution_id'))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_subject_institution_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_subjects_institution_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_code'))
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=1)
        batch_op.alter_column('institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_achievements_institution_id'))

    # ### end Alembic commands ###
