"""add_shift_and_hours_per_week

Revision ID: b3fcf0c40f8c
Revises: 998ad443b9f7
Create Date: 2026-04-22 19:05:30.507855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fcf0c40f8c'
down_revision = '998ad443b9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Grades table: add shift and update unique constraint
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_grades_shift'), ['shift'], unique=False)
        # Handle constraint name change safely in SQLite
        batch_op.create_unique_constraint('uq_grade_campus_year_shift', ['campus_id', 'name', 'academic_year', 'shift'])
        # Drop old constraint if possible, but SQLite batch might handle it or error
        # batch_op.drop_constraint('uq_grade_campus_year', type_='unique')

    # Schedule Blocks table: add shift and update unique constraint
    with op.batch_alter_table('schedule_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_schedule_blocks_shift'), ['shift'], unique=False)
        batch_op.create_unique_constraint('uq_block_campus_name_year_shift', ['campus_id', 'name', 'academic_year', 'shift'])
        # batch_op.drop_constraint('uq_block_campus_name_year', type_='unique')

    # Subject Grades table: add hours_per_week
    with op.batch_alter_table('subject_grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_per_week', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('subject_grades', schema=None) as batch_op:
        batch_op.drop_column('hours_per_week')

    with op.batch_alter_table('schedule_blocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_block_campus_name_year_shift', type_='unique')
        batch_op.drop_index(batch_op.f('ix_schedule_blocks_shift'))
        batch_op.drop_column('shift')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('uq_grade_campus_year_shift', type_='unique')
        batch_op.drop_index(batch_op.f('ix_grades_shift'))
        batch_op.drop_column('shift')

    # ### end Alembic commands ###
