"""streamline_student_profile_and_optional_email

Revision ID: eb140e639646
Revises: d77ba5cae966
Create Date: 2026-04-24 10:55:19.834565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb140e639646'
down_revision = 'd77ba5cae966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_students', schema=None) as batch_op:
        batch_op.drop_index('ix_academic_students_document_number')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('document_number')
        batch_op.drop_column('gender')
        batch_op.drop_column('document_type')
        batch_op.drop_column('address')
        batch_op.drop_column('photo')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('country', server_default=None)
        batch_op.alter_column('must_change_password', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')

    with op.batch_alter_table('academic_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('document_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('document_number', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), nullable=True))
        batch_op.create_index('ix_academic_students_document_number', ['document_number'], unique=1)
    # ### end Alembic commands ###
